language: python
python: "3.5"
env:
 - TOX_ENV=py27
 - TOX_ENV=py34
 - TOX_ENV=py35
 - TOX_ENV=coverage
 - TOX_ENV=docs
 - TOX_ENV=pylint
 - TOX_ENV=packaging
install: pip install tox
script: tox -e $TOX_ENV
